// apps/desktop/src/components/windows/Camera.tsx
import React, { useEffect, useRef, useState } from "react";
import { useMediaDevices } from "@/utils/recording/MediaDeviceContext";
import { CloseX } from "@/components/icons/CloseX";

export const Camera = () => {
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const { selectedVideoDevice } = useMediaDevices();
  const [isLoading, setIsLoading] = useState(true);
  const tauriWindowImport = import("@tauri-apps/api/window");

  useEffect(() => {
    if (!videoRef.current || !selectedVideoDevice) return;
    const video = videoRef.current;
    const constraints = {
      video: {
        deviceId: selectedVideoDevice.deviceId,
      },
    };

    navigator.mediaDevices
      .getUserMedia(constraints)
      .then((stream) => {
        video.srcObject = stream;
        video.play();
        setIsLoading(false);
      })
      .catch((err) => {
        console.error(err);
      });

    return () => {
      if (video.srcObject) {
        const stream = video.srcObject as MediaStream;
        stream.getTracks().forEach((track) => {
          track.stop();
        });
      }
    };
  }, [selectedVideoDevice]);

  const setWindowSize = async (type: "sm" | "lg") => {
    tauriWindowImport.then(
      ({ currentMonitor, appWindow, LogicalSize, LogicalPosition }) => {
        currentMonitor().then((monitor) => {
          const windowWidth = type === "sm" ? 230 : 400;
          const windowHeight = type === "sm" ? 230 : 400;

          if (monitor && monitor.size) {
            const scalingFactor = monitor.scaleFactor;
            const x = 100;
            const y = monitor.size.height / scalingFactor - windowHeight - 100;

            console.log(
              scalingFactor,
              x,
              y,
              windowWidth,
              windowHeight,
              monitor
            );

            appWindow.setSize(new LogicalSize(windowWidth, windowHeight));
            appWindow.setPosition(new LogicalPosition(x / scalingFactor, y));
          }
        });
      }
    );
  };

  const closeWindow = () => {
    import("@tauri-apps/api/window").then(({ appWindow }) => {
      appWindow.close();
    });
  };

  return (
    <div
      data-tauri-drag-region
      className="group w-full h-full bg-gray-200 rounded-full m-0 p-0 relative overflow-hidden flex items-center justify-center border-none outline-none focus:outline-none"
    >
      {isLoading && (
        <div className="w-full h-full absolute top-0 left-0 bg-gray-200 z-10 flex items-center justify-center">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            stroke="#fff"
            viewBox="0 0 38 38"
            className="w-24 h-24"
          >
            <g
              fill="none"
              fillRule="evenodd"
              strokeWidth="2"
              transform="translate(1 1)"
            >
              <circle cx="18" cy="18" r="18" strokeOpacity="0.4"></circle>
              <path d="M36 18c0-9.94-8.06-18-18-18">
                <animateTransform
                  attributeName="transform"
                  dur="1s"
                  from="0 18 18"
                  repeatCount="indefinite"
                  to="360 18 18"
                  type="rotate"
                ></animateTransform>
              </path>
            </g>
          </svg>
        </div>
      )}
      <div className="opacity-0 group-hover:opacity-100 absolute top-3 left-1/2 transform -translate-x-1/2 bg-gray-800 rounded-xl z-20 grid grid-cols-3 overflow-hidden">
        <div
          onClick={() => {
            closeWindow();
          }}
          className="h-full flex items-center justify-center p-2 hover:bg-gray-900"
        >
          <div>
            <CloseX className="w-5 h-5 stroke-gray-200" />
          </div>
        </div>
        <div
          onClick={async () => {
            await setWindowSize("sm");
          }}
          className="h-full flex items-center justify-center p-2 hover:bg-gray-900"
        >
          <span className="w-1 h-1 m-0 p-0 bg-gray-200 rounded-full"></span>
        </div>
        <div
          onClick={async () => {
            await setWindowSize("lg");
          }}
          className="h-full flex items-center justify-center p-2 hover:bg-gray-900"
        >
          <span className="w-3 h-3 bg-gray-200 rounded-full"></span>
        </div>
      </div>
      <canvas
        ref={canvasRef}
        className="absolute top-0 left-0 w-full h-full object-cover pointer-events-none"
      ></canvas>
      <video
        ref={videoRef}
        autoPlay
        playsInline
        muted
        className="absolute top-0 left-0 w-full h-full object-cover pointer-events-none"
      />
    </div>
  );
};

// apps/desktop-solid/src/routes/camera.tsx
import { makePersisted } from "@solid-primitives/storage";
import {
  LogicalPosition,
  LogicalSize,
  currentMonitor,
  getCurrentWindow,
} from "@tauri-apps/api/window";
import { Show, createEffect, createResource, createSignal, on } from "solid-js";
import { createStore } from "solid-js/store";

import { CloseX, Expand, Flip, Minimize, Squircle } from "../icons";
import { createCameraForLabel } from "../utils/media";
import { createOptionsQuery } from "../utils/queries";
import { commands } from "../utils/tauri";

namespace CameraWindow {
  export type Size = "sm" | "lg";
  export type Shape = "round" | "square";
  export type State = {
    size: Size;
    shape: Shape;
    mirrored: boolean;
  };
}

export default function () {
  const options = createOptionsQuery();

  const camera = createCameraForLabel(() => options.data?.cameraLabel ?? "");

  const [cameraPreviewRef] = createCameraPreview(() => camera()?.deviceId);

  const [state, setState] = makePersisted(
    createStore<CameraWindow.State>({
      size: "sm",
      shape: "round",
      mirrored: false,
    })
  );

  createEffect(on(() => state.size, resizeWindow));

  return (
    <Show when={options.data}>
      {(options) => (
        <div
          data-tauri-drag-region
          class="cursor-move group w-screen h-screen bg-gray-200 m-0 p-0 relative overflow-hidden flex items-center justify-center outline-none focus:outline-none border-2 border-sm border-gray-300"
          style={{ "border-radius": cameraBorderRadius(state) }}
        >
          <div class="opacity-0 group-hover:opacity-100 absolute top-5 left-1/2 transform -translate-x-1/2 bg-gray-800 bg-opacity-75 backdrop-blur-sm rounded-xl z-20 grid grid-cols-4 overflow-hidden transition-opacity">
            <div
              onClick={() => {
                commands.setRecordingOptions({
                  ...options(),
                  cameraLabel: null,
                });
              }}
              class="h-full flex items-center justify-center p-2 hover:bg-gray-900"
            >
              <div>
                <CloseX class="w-5 h-5 stroke-gray-200" />
              </div>
            </div>
            <div
              onClick={() => {
                setState("size", (s) => (s === "sm" ? "lg" : "sm"));
              }}
              class="h-full flex items-center justify-center p-2 hover:bg-gray-900"
            >
              <div>
                {state.size === "sm" ? (
                  <Expand class="w-5 h-5 stroke-gray-200" />
                ) : (
                  <Minimize class="w-5 h-5 stroke-gray-200" />
                )}
              </div>
            </div>
            <div
              onClick={() =>
                setState("shape", (s) => (s === "round" ? "square" : "round"))
              }
              class="h-full flex items-center justify-center p-2 hover:bg-gray-900"
            >
              {state.shape === "round" ? (
                <div>
                  <Squircle class="w-5 h-5 stroke-gray-200" />
                </div>
              ) : (
                <span class="w-3 h-3 bg-gray-200 rounded-full" />
              )}
            </div>
            <div
              onClick={() => setState("mirrored", (m) => !m)}
              class="h-full flex items-center justify-center p-2 hover:bg-gray-900"
            >
              <div>
                <Flip class="w-5 h-5 stroke-gray-200" />
              </div>
            </div>
          </div>

          <video
            data-tauri-drag-region
            autoplay
            playsinline
            muted
            class={
              "absolute top-0 left-0 w-full h-full object-cover pointer-events-none"
            }
            style={{ transform: state.mirrored ? "scaleX(1)" : "scaleX(-1)" }}
            ref={cameraPreviewRef}
          />
        </div>
      )}
    </Show>
  );
}

function cameraBorderRadius(state: CameraWindow.State) {
  if (state.shape === "round") return "9999px";
  if (state.size === "sm") return "3rem";
  return "4rem";
}

async function resizeWindow(size: CameraWindow.Size) {
  const monitor = await currentMonitor();

  const windowWidth = size === "sm" ? 230 : 400;
  const windowHeight = size === "sm" ? 230 : 400;

  if (!monitor) return;

  const scalingFactor = monitor.scaleFactor;
  const x = 100;
  const y = monitor.size.height / scalingFactor - windowHeight - 100;

  console.log(scalingFactor, x, y, windowWidth, windowHeight, monitor);

  const currentWindow = getCurrentWindow();
  currentWindow.setSize(new LogicalSize(windowWidth, windowHeight));
  currentWindow.setPosition(new LogicalPosition(x / scalingFactor, y));
}

function createCameraPreview(deviceId: () => string | undefined) {
  const [cameraStream] = createResource(
    deviceId,

    (cameraInputId) =>
      navigator.mediaDevices.getUserMedia({
        video: { deviceId: cameraInputId },
      })
  );

  const [cameraRef, setCameraRef] = createSignal<HTMLVideoElement>();

  createEffect(() => {
    const stream = cameraStream();
    const ref = cameraRef();

    if (ref && stream) {
      if (ref.srcObject === stream) return;
      ref.srcObject = stream;
      ref.play();
    }
  });

  return [setCameraRef] as const;
}
